In [1]:
%load_ext autoreload
%autoreload 2

# Error tail fitting for finite difference calculations

From the equation of the finite difference, we cam see that there is a linear error tail for the forward and backward only finite difference calculations and a quadratic error tail for central finite difference.
When taking a derivative of a numerical functions on can simply reduce the error by using a very small delta.
However, the noises from the DFT computation dominate when using very small displacement amplitute, and the higher order influence becomes non-neglegible when the amplitute gets larger.

Thus, we need to compute the derivative at a series of deltas and fit the error tails to extrapolate $\delta\to0$ for the true derivative.

Since at some delta points, the finite displacement result is so affected by noises, we need to discard those points during the fitting procedure. The most straightforward approach is to pick a number of delta points and find the best fit among them.

In [2]:
import numpy as np
from principia_materia.mathematics import errortail
from principia_materia.mathematics.errortail import get_errortail

In [3]:
deltas = np.arange(10) / 100 + 0.01
values = np.array([
    [0.5488135 , 0.79172504],
    [0.71518937, 0.52889492],
    [0.60276338, 0.56804456],
    [0.54488318, 0.92559664],
    [0.4236548 , 0.07103606],
    [0.64589411, 0.0871293 ],
    [0.43758721, 0.0202184 ],
    [0.891773  , 0.83261985],
    [0.96366276, 0.77815675],
    [0.38344152, 0.87001215]])

In [11]:
get_errortail(
    deltas=deltas,
    values=values,
    pick_min=3,
    pick_max=5,
    return_xcoef=True,
    return_pick=True,
    return_penalty=True,
)

(array([0.76973244+0.j, 0.78883914+0.j]),
 array([-138.99332838+0.j,    7.74785591+0.j]),
 array([array([1.+0.j, 3.+1.j, 4.+2.j]), array([0.+0.j, 7.+1.j, 9.+2.j])],
       dtype=object),
 array([3.04622804e-06+0.j, 1.72701298e-05+0.j]))

In [ ]:
help(errortail)