# Mathematical functions

There are some key mathematical functions that are frequently used throughout the package but not available
in libraries like numpy. Thus, we define them here.

## Gram–Schmidt Orthonormalization

Function `gs_orthog` orthonormalizes the input row vectors, when `allow_zero=True`, it allows linearly dependent rows, otherwise it will throw a `ZeroDivisionError` error.

In [1]:
import numpy as np
from principia_materia.mathematics import gs_orthog

In [4]:
vectors =  np.array([
    [1, 0, 0],
    [1, 1, 0],
    [1, 0, 1],
    [1, 1, 1],
], float)

In [15]:
try:
    gs_orthog(vectors)
except ZeroDivisionError as e:
    print("Caught an error:\n\t {0.__class__.__name__}: {0!s}".format(e))

Caught an error:
	 ZeroDivisionError: Vectors are not linearly independent.


In [6]:
gs_orthog(vectors, allowzero=True)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

## Smith Normal Form & Hermite Normal Form

Smith normal form is a diagonal form of a integer matrix, with only row and column transformations.
This is a crucial property of integer matrices that is used in our minimum supercell theorem.
Meanwhile, Hermite normal form is the upper/lower triangular form of integer matrices with only row/colum transformations. This is also an important mathematical tool in finding the minimum super cell as well as finding the translations within a supercell.

Wiki:
[Smith Normal Form](https://en.wikipedia.org/wiki/Smith_normal_form),
[Hermite Normal Form](https://en.wikipedia.org/wiki/Hermite_normal_form)

In [17]:
from principia_materia.mathematics import SmithNormalForm, HermiteNormalForm_AU, HermiteNormalForm_UA

In [18]:
matrix = np.array([
    [1, 2, 3],
    [3, 4, 5],
    [5, 6, 7],
])

Smith normal form and the row & column transformation:

In [19]:
SmithNormalForm(matrix)

(array([[1, 0, 0],
        [0, 2, 0],
        [0, 0, 0]]),
 array([[ 1,  0,  0],
        [ 3, -1,  0],
        [-1,  2, -1]]),
 array([[ 1, -2,  1],
        [ 0,  1, -2],
        [ 0,  0,  1]]))

Column Hermite normal form and the column transformation:

In [20]:
HermiteNormalForm_AU(matrix)

(array([[1, 0, 0],
        [1, 2, 0],
        [1, 4, 0]]),
 array([[-1,  2, -1],
        [ 1, -1,  2],
        [ 0,  0, -1]]))

Row Hermite form and the row transformation:

In [21]:
HermiteNormalForm_UA(matrix)

(array([[ 1,  0, -1],
        [ 0,  2,  4],
        [ 0,  0,  0]]),
 array([[-2,  1,  0],
        [ 3, -1,  0],
        [-1,  2, -1]]))