# Fourier Interpolation


When we compute phonons and their interactions, we construct a FTG and find the coefficients within it.
Fourier interpolation allows us to interpolate the interactions from this discrete grid to continum (i.e. infinite crystal), to study materials properties, including dynamics and thermaldynamics.

First, we Fourier transform the dynamic matrices from reciprocal space to real space, this gives us the force constant tensors at a given range and order. However, these forces has to respect space group symmetry, and the Fourier transform and periodic boundary condition of the FTG do not. 
There is not unique approach on how to enforce the space group symmetry of the force tensors.
We propose a most straightforward approach to repack them into the Wigner Seitz cell of the FTG.


In this `FourierInterpolation` class:
1. If dynamic matrices of the irreducible Q-points are provided, the rest of the zone will be 
    computed from the irreducible counterpart using space group symmetry. Then Fourier transformed into real space.
2. If dynamic matrices of all the Q-points in FTG, they will be Fourier transformed into real space.
3. If force constants tensors of the FTG, no extra action is needed.

The Wigner Seitz map contains the information of the real space T-points that have non-zero force constants and their weight in terms of the force constants within FTG.

The resulting force constants tensors can be used to compute Grüneisen parameters, phonon linewidth etc. as well as being used in MD simulations.


In [2]:
import numpy as np
from principia_materia.io_interface.vasp import parse_poscar
from principia_materia.translation_group import get_structure, CrystalFTG
from principia_materia.phonon_id.fourier_interpolation import FourierInterpolation

In [3]:
structure = get_structure(parse_poscar("nacl/POSCAR"), stype=CrystalFTG)
structure.orbitals = "p"

In [14]:
supa = np.array([
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, 1]])

In [11]:
fi = FourierInterpolation(
    structure=structure,
    supa=supa,
    pg="Oh",
    order=2,
)
fi.set_Wigner_Seitz_map()

In [13]:
fi._Phi_WS_map

OrderedDict([(((0, 0, 0), (0, 0, 0)),
              array([[1., 0.],
                     [0., 1.]])),
             (((0, 0, 0), (-1, 0, -1)),
              array([[0.        , 0.16666667],
                     [0.        , 0.        ]])),
             (((0, 0, 0), (0, -1, 0)),
              array([[0.        , 0.16666667],
                     [0.        , 0.        ]])),
             (((0, 0, 0), (0, -1, -1)),
              array([[0.        , 0.16666667],
                     [0.        , 0.        ]])),
             (((0, 0, 0), (-1, -1, 0)),
              array([[0.        , 0.16666667],
                     [0.        , 0.        ]])),
             (((0, 0, 0), (0, 0, -1)),
              array([[0.        , 0.16666667],
                     [0.        , 0.        ]])),
             (((0, 0, 0), (-1, 0, 0)),
              array([[0.        , 0.16666667],
                     [0.        , 0.        ]])),
             (((0, 0, 0), (0, 1, 1)),
              array([[0.        , 0.    