# Symmetry analysis of phonon interactions

In [17]:
import numpy as np
np.set_printoptions(linewidth=180, suppress=True)
from principia_materia import Fraction
from principia_materia.io_interface import parse_array
from principia_materia.translation_group import CrystalFTG
from principia_materia.io_interface.qpoints_io import tuple_to_str
from principia_materia.phonon_id.little_group_adt import LittleGroupADT
from principia_materia.phonon_id.analytic_tensors import AnalyticTensors
from principia_materia.phonon_id.chainrule_derivatives import ChainruleDerivatives

In [2]:
lattice_vectors = np.array([
    [0.0, 0.5, 0.5],
    [0.5, 0.0, 0.5],
    [0.5, 0.5, 0.0],
])
atoms = {
    "Na": np.array([[0.0, 0.0, 0.0]]),
    "Cl": np.array([[0.5, 0.5, 0.5]]),
}
supa = np.identity(3, dtype=int)
orbitals = "p"
structure = CrystalFTG(vec=lattice_vectors, atoms=atoms, supa=supa, orbitals=orbitals)

## Analytic dynamic tensor

Analytic dynamic tensor allows us to perform symmetry analysis of the phonon interactions at a given Q-point, and determine the irreducible derivatives allowed by symmetry and the the coefficients of the tensor elements with respect to the irreducible derivatives. 
Additionally, the vectorized tensor form facilitates linear operations, making it useful in further analysis.

## Little group ADT

Analytic dynamic tensor with little group symmetry analysis approach.


1. Second order: ($L_x$, $L_x$)

In [3]:
Qpoint = parse_array("1/2 0 0; 1/2 0 0", dtype=Fraction)
Qpoint

[[Fraction(1, 2), Fraction(0, 1), Fraction(0, 1)],
 [Fraction(1, 2), Fraction(0, 1), Fraction(0, 1)]]

In [4]:
lgadt = LittleGroupADT(
    structure=structure,
    pg="Oh",
    Qpoint=Qpoint)
lgadt.set_qpoint_displacement_rep()
lgadt.set_irreducible_derivatives()
lgadt.set_vectorized_tensor()

In [5]:
lgadt.irreducible_derivative_names

[((((Fraction(1, 2), Fraction(0, 1), Fraction(0, 1)), ('A1g', 0)),
   ((Fraction(1, 2), Fraction(0, 1), Fraction(0, 1)), ('A1g', 0))),
  ('A1g', 0)),
 ((((Fraction(1, 2), Fraction(0, 1), Fraction(0, 1)), ('Eg', 0)),
   ((Fraction(1, 2), Fraction(0, 1), Fraction(0, 1)), ('Eg', 0))),
  ('A1g', 0)),
 ((((Fraction(1, 2), Fraction(0, 1), Fraction(0, 1)), ('A2u', 0)),
   ((Fraction(1, 2), Fraction(0, 1), Fraction(0, 1)), ('A2u', 0))),
  ('A1g', 0)),
 ((((Fraction(1, 2), Fraction(0, 1), Fraction(0, 1)), ('Eu', 0)),
   ((Fraction(1, 2), Fraction(0, 1), Fraction(0, 1)), ('Eu', 0))),
  ('A1g', 0))]

In [6]:
lgadt.vectorized_tensor.shape

(6, 6, 4)

In [7]:
for i in range(lgadt.n_irreducible_derivatives):
    print(i)
    print(lgadt.vectorized_tensor[:, :, i].real)

0
[[ 0.          0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.33333333 -0.33333333 -0.33333333]
 [ 0.          0.          0.         -0.33333333  0.33333333  0.33333333]
 [ 0.          0.          0.         -0.33333333  0.33333333  0.33333333]]
1
[[ 0.          0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.66666667  0.33333333  0.33333333]
 [ 0.          0.          0.          0.33333333  0.66666667 -0.33333333]
 [ 0.          0.          0.          0.33333333 -0.33333333  0.66666667]]
2
[[ 0.33333333 -0.33333333 -0.33333333  0.          0.          0.        ]
 [-0.33333333  0.

2. Third order: ($\Gamma$, $L_x$, $L_x$)

In [8]:
Qpoint = parse_array("0 0 0; 1/2 0 0; 1/2 0 0", dtype=Fraction)
Qpoint

[[Fraction(0, 1), Fraction(0, 1), Fraction(0, 1)],
 [Fraction(1, 2), Fraction(0, 1), Fraction(0, 1)],
 [Fraction(1, 2), Fraction(0, 1), Fraction(0, 1)]]

In [9]:
lgadt = LittleGroupADT(
    structure=structure,
    pg="Oh",
    Qpoint=Qpoint)
lgadt.set_qpoint_displacement_rep()
lgadt.set_irreducible_derivatives()
lgadt.set_vectorized_tensor()

In [10]:
lgadt.irreducible_derivative_names

[((((Fraction(0, 1), Fraction(0, 1), Fraction(0, 1)), ('A2u', 0)),
   ((Fraction(1, 2), Fraction(0, 1), Fraction(0, 1)), ('A1g', 0)),
   ((Fraction(1, 2), Fraction(0, 1), Fraction(0, 1)), ('A2u', 0))),
  ('A1g', 0)),
 ((((Fraction(0, 1), Fraction(0, 1), Fraction(0, 1)), ('A2u', 0)),
   ((Fraction(1, 2), Fraction(0, 1), Fraction(0, 1)), ('Eg', 0)),
   ((Fraction(1, 2), Fraction(0, 1), Fraction(0, 1)), ('Eu', 0))),
  ('A1g', 0)),
 ((((Fraction(0, 1), Fraction(0, 1), Fraction(0, 1)), ('Eu', 0)),
   ((Fraction(1, 2), Fraction(0, 1), Fraction(0, 1)), ('A1g', 0)),
   ((Fraction(1, 2), Fraction(0, 1), Fraction(0, 1)), ('Eu', 0))),
  ('A1g', 0)),
 ((((Fraction(0, 1), Fraction(0, 1), Fraction(0, 1)), ('Eu', 0)),
   ((Fraction(1, 2), Fraction(0, 1), Fraction(0, 1)), ('A2u', 0)),
   ((Fraction(1, 2), Fraction(0, 1), Fraction(0, 1)), ('Eg', 0))),
  ('A1g', 0)),
 ((((Fraction(0, 1), Fraction(0, 1), Fraction(0, 1)), ('Eu', 0)),
   ((Fraction(1, 2), Fraction(0, 1), Fraction(0, 1)), ('Eg', 0)),
   ((F

## Analytic tensors within a given FTG at a given order

For symmetry analysis of the FTG, one would start by constructing analytic dynamic tensors of the irreducible Q-points withith the FTG, and compute for the rest of the brillouin zone by rotating from the corresponding irreducible Q-points.

In [11]:
supa = np.diag([2, 2, 2])
at = AnalyticTensors(
    structure=structure,
    supa=supa,
    order=2,
    pg="Oh",
)
at.set_ADT(
    little_group=True,
    verbose=True,
)

Computing ADT for Qpoint: ((0, 0, 0), (0, 0, 0))
Computing ADT for Qpoint: ((1/2, 0, 0), (1/2, 0, 0))
Computing ADT for Qpoint: ((1/2, 1/2, 0), (1/2, 1/2, 0))
Summarize irreducible derivatives.
Compute vectorized tensors.


In [18]:
for irreducible_derivative in at.irreducible_derivative_names:
    print(tuple_to_str(irreducible_derivative))

((((0, 0, 0), (T1u, 0)), ((0, 0, 0), (T1u, 0))), (A1g, 0))
((((1/2, 0, 0), (A1g, 0)), ((1/2, 0, 0), (A1g, 0))), (A1g, 0))
((((1/2, 0, 0), (Eg, 0)), ((1/2, 0, 0), (Eg, 0))), (A1g, 0))
((((1/2, 0, 0), (A2u, 0)), ((1/2, 0, 0), (A2u, 0))), (A1g, 0))
((((1/2, 0, 0), (Eu, 0)), ((1/2, 0, 0), (Eu, 0))), (A1g, 0))
((((1/2, 1/2, 0), (A2u, 0)), ((1/2, 1/2, 0), (A2u, 0))), (A1g, 0))
((((1/2, 1/2, 0), (A2u, 0)), ((1/2, 1/2, 0), (A2u, 1))), (A1g, 0))
((((1/2, 1/2, 0), (A2u, 1)), ((1/2, 1/2, 0), (A2u, 1))), (A1g, 0))
((((1/2, 1/2, 0), (Eu, 0)), ((1/2, 1/2, 0), (Eu, 0))), (A1g, 0))
((((1/2, 1/2, 0), (Eu, 0)), ((1/2, 1/2, 0), (Eu, 1))), (A1g, 0))
((((1/2, 1/2, 0), (Eu, 1)), ((1/2, 1/2, 0), (Eu, 1))), (A1g, 0))


## Chainrule derivatives

With the analytic tensors of the FTG, we are able to perform further analysis on phonon interactions.
One of them is using chainrule derivatives to compute the transformation matrices for abitrary displacements for BID approach.

In [19]:
supa = np.ones((3, 3), dtype=int) - 2 * np.identity(3, dtype=int)
chainrule =  ChainruleDerivatives(
    structure=structure,
    supa=supa,
    order=2,
    pg='Oh')
chainrule.set_ADT(verbose=True)
chainrule.set_basis()

Computing ADT for Qpoint: ((0, 0, 0), (0, 0, 0))
Computing ADT for Qpoint: ((1/2, 1/2, 0), (1/2, 1/2, 0))
Summarize irreducible derivatives.
Compute vectorized tensors.


In [20]:
displacements = np.zeros((1, chainrule.order - 1, chainrule.supercell.natoms, chainrule.supercell.dim))
displacements[0, 0, 0, 0] = 1

In [21]:
matrix = chainrule.compute_chainrule(displacements)

In [22]:
matrix.reshape((-1, chainrule.n_irreducible_derivatives)).real

array([[ 0.25,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [-0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [-0.25,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [-0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.5 , -0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  , -0.  ,  0.  ,  0.  ],
       [ 0.  , -0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.5 , -0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  , -0.  ,  0.  ],
       [ 0.  ,  0.  , -0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.5 ,  0.  ,  0.  ],
       [ 0.  , -0.  , -0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  , -0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.5 ,  0.  ],
       [ 0.  ,  0.  , -0.  , -0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,