# Representations

Representation is the foundation of all our group theory analysis.
The goal is for a given representation to decompose for the irreducible representation, which contains complete information of the original in the most concise way.

Here we present several core representation classes we use throught out the package.

## Cluster represntation

We can form the point group representations of a cluster and decompose them into irreducible representations, 
allowing us to analyze the symmetry of the cluster.
Furthermore, we can execute (symmetry) direct product the cluster representation with representation for more advanced analysis. For example, the displacement representation of a cluster is the direct product representation of the cluster representation and the representation of the atomic displacement.

Here we look at an example of the in-plane displacement of a square cluster of C atoms under $C_{4v}$ point group.

In [3]:
import numpy as np
from principia_materia.translation_group import Cluster
from principia_materia.representation import ClusterRep

In [4]:
atoms = {
    "C": np.array([
        [ 0.5,  0.5, 0.0],
        [-0.5,  0.5, 0.0],
        [-0.5, -0.5, 0.0],
        [ 0.5, -0.5, 0.0],
    ])
}
cluster = Cluster(atoms=atoms, orbitals="p_x,p_y")

In [5]:
cluster_rep = ClusterRep(cluster=cluster, pg="C4v")

The irreducible representation of the square cluster representation is:
$$A_1 \oplus B_2 \oplus E_1$$

In [6]:
cluster_rep.irrep_counter

OrderedDict([('A1', 1), ('B2', 1), ('E', 1)])

And the irreducible basis is as follows:

In [7]:
cluster_rep.construct_irreducible_basis()

In [8]:
cluster_rep.irrvec_dict

OrderedDict([(('A1', 0), array([[0.5, 0.5, 0.5, 0.5]])),
             (('B2', 0), array([[ 0.5, -0.5,  0.5, -0.5]])),
             (('E', 0),
              array([[ 0.5, -0.5, -0.5,  0.5],
                     [ 0.5,  0.5, -0.5, -0.5]]))])

In [10]:
cluster_rep = ClusterRep(cluster=cluster, pg="C2v")

In [11]:
cluster_rep.irrep_counter

OrderedDict([('A1', 2), ('B1', 1)])

## Cluster displacements represntation

Displacement representation of the point group in a cluster allows us to analyze the symmetry of atomic displacement in a cluster.

We continue with the above example of the square.

In [2]:
from principia_materia.representation import DispClusterRep

In [14]:
disp_cluster_rep = DispClusterRep(cluster=cluster, pg="C4v")

We can decompose the displacement representation of the cluster into irreducible representations:
$$A_1 \oplus B_1 \oplus A_2 \oplus B_2 \oplus 2 E$$

In [15]:
disp_cluster_rep.irrep_counter

OrderedDict([('A1', 1), ('B1', 1), ('A2', 1), ('B2', 1), ('E', 2)])

Below are the displacement vectors of the irreducible representations:

In [16]:
disp_cluster_rep.construct_irreducible_basis()

In [17]:
disp_cluster_rep.irrvec_dict

OrderedDict([(('A1', 0),
              array([[ 0.35355339,  0.35355339, -0.35355339,  0.35355339, -0.35355339,
                      -0.35355339,  0.35355339, -0.35355339]])),
             (('B1', 0),
              array([[ 0.35355339, -0.35355339, -0.35355339, -0.35355339, -0.35355339,
                       0.35355339,  0.35355339,  0.35355339]])),
             (('A2', 0),
              array([[ 0.35355339, -0.35355339,  0.35355339,  0.35355339, -0.35355339,
                       0.35355339, -0.35355339, -0.35355339]])),
             (('B2', 0),
              array([[ 0.35355339,  0.35355339,  0.35355339, -0.35355339, -0.35355339,
                      -0.35355339, -0.35355339,  0.35355339]])),
             (('E', 0),
              array([[0.5, 0. , 0.5, 0. , 0.5, 0. , 0.5, 0. ],
                     [0. , 0.5, 0. , 0.5, 0. , 0.5, 0. , 0.5]])),
             (('E', 1),
              array([[ 0. ,  0.5,  0. , -0.5,  0. ,  0.5,  0. , -0.5],
                     [ 0.5,  0. , -0.5,  0. 

## Direct product represntation

`DirectProduct` computes the direct product of a set of irreducible representations and decompose the result.

In [18]:
from principia_materia.representation import DirectProduct

In [25]:
direct_product = DirectProduct(
    pg="C6v",
    irrep_inputs=["E1", "E1"],
)

For example, under $C_{6v}$ point group:
$$E_1 \otimes E_1 = A_1 \oplus A_2 \oplus E_2$$

In [26]:
direct_product.irrep_counter

OrderedDict([('A1', 1), ('A2', 1), ('E2', 1)])

In [27]:
direct_product.construct_irreducible_basis()

In [28]:
direct_product.irrvec_dict

OrderedDict([(('A1', 0),
              array([[0.70710678, 0.        , 0.        , 0.70710678]])),
             (('A2', 0),
              array([[ 0.        ,  0.70710678, -0.70710678,  0.        ]])),
             (('E2', 0),
              array([[ 0.        ,  0.70710678,  0.70710678,  0.        ],
                     [ 0.70710678,  0.        ,  0.        , -0.70710678]]))])

## Symmetric direct product representation

In [19]:
from principia_materia.representation import SymmetricDirectProduct

In [29]:
sym_direct_product = SymmetricDirectProduct(
    pg="C6v",
    irrep_inputs=["E1", "E1"],
)

For example, under $C_{6v}$ point group, we have the symmetric direct product:
$$E_1 \odot E_1 = A_1 \oplus E_2$$

In [30]:
sym_direct_product.irrep_counter

OrderedDict([('A1', 1), ('E2', 1)])

In [31]:
sym_direct_product.construct_irreducible_basis()

In [32]:
sym_direct_product.irrvec_dict

OrderedDict([(('A1', 0), array([[0.70710678, 0.        , 0.70710678]])),
             (('E2', 0),
              array([[ 0.        ,  1.        ,  0.        ],
                     [ 0.70710678,  0.        , -0.70710678]]))])

## CharmBlochRep

`CharmBlochRep` finds the real space point group representation of a translationally invariant set of orbitals for a given q-point. The point operations will map a given q-point to a different q-point.

Here is an example with rocksalt at Gamma point.

In [22]:
from principia_materia.io_interface.vasp import parse_poscar
from principia_materia.translation_group import get_structure, CrystalFTG
from principia_materia.representation import CharmBlochRep

In [36]:
structure = get_structure(parse_poscar("nacl/POSCAR"), stype=CrystalFTG)
structure.orbitals = "p"

First we construct the representation, and find the p orbitals in rocksalt transform like $2 T_{1u}$ in $O_h$ point group.
The irreducible basis also shows that each $T_{1u}$ representaion the each atom of the rocksalt.

In [38]:
cbr = CharmBlochRep(
    structure=structure,
    pg="Oh",
    qpoint=np.array([0, 0, 0]),
)

In [39]:
cbr.irrep_counter

OrderedDict([('T1u', 2)])

In [40]:
cbr.construct_irreducible_basis()

In [41]:
cbr.irrvec_dict

OrderedDict([(('T1u', 0),
              array([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
                     [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
                     [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]])),
             (('T1u', 1),
              array([[0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j],
                     [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],
                     [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j]]))])

Crystal nuclei vibrations also transform like "p" orbitals.
In the case of a free crystal, we can impose the acoustic sum rule and the acoustic modes at Gamma point can be isolated, and have phonon frequencies of 0.
These acoustic modes at Gamma point can't couple with other modes, so we can remove them when analyzing phonons and their interactions.

In [42]:
cbr.orthogonalize_shift_modes(remove=True)

In [43]:
cbr.irrvec_dict

OrderedDict([(('T1u', 0),
              array([[ 0.70710678+0.j,  0.        +0.j,  0.        +0.j,
                      -0.70710678+0.j,  0.        +0.j,  0.        +0.j],
                     [ 0.        +0.j,  0.70710678+0.j,  0.        +0.j,
                       0.        +0.j, -0.70710678+0.j,  0.        +0.j],
                     [ 0.        +0.j,  0.        +0.j,  0.70710678+0.j,
                       0.        +0.j,  0.        +0.j, -0.70710678+0.j]]))])

## Shift Mode

`ShiftMode` constructs the shift modes for a given list of orbitals 
(orbitals can only be from "p_x", "p_y", "p_z").
This is used to remove shift modes from `DispClusterRep` and `CharmBlochRep`.

In [1]:
from principia_materia.representation import ShiftMode

In [2]:
sm = ShiftMode(
  pg="D4h",
  orbitals=list("p_x p_y".split()) * 2,
  )
sm.set_shift_mode_vectors()

In [3]:
sm.shift_mode_irrep_counter

OrderedDict([('Eu', 1)])

In [4]:
sm.shift_mode_vectors

OrderedDict([(('Eu', 0),
              array([[0.70710678, 0.        , 0.70710678, 0.        ],
                     [0.        , 0.70710678, 0.        , 0.70710678]]))])