In [1]:
%load_ext autoreload

In [2]:
%autoreload 2

In [3]:
from principia_materia.translation_group import LatticeFTG, Kpoints

In [4]:
lattice_vecs = np.array([[np.sqrt(3)/2, 0.5, 0], [np.sqrt(3)/2, -0.5, 0], [0, 0, 10]])
lattice_vecs

array([[ 0.8660254,  0.5      ,  0.       ],
       [ 0.8660254, -0.5      ,  0.       ],
       [ 0.       ,  0.       , 10.       ]])

In [5]:
supa = np.array([
    [1, 1, 0],
    [0, 3, 0],
    [0, 0, 1]
])

In [7]:
from principia_materia.kpoints.kmesh import KMesh

In [8]:
km = KMesh(supa=supa, lattice_vecs=lattice_vecs, pgn="D6h")

In [9]:
km.kvecs_ibz_int

array([[0, 0, 0],
       [1, 1, 0]])

In [11]:
km.kvecs_int

array([[0, 0, 0],
       [1, 1, 0],
       [1, 2, 0]])

In [72]:
kpts = Kpoints(vec=lattice_vecs, supa=supa, pg="D6h")

In [73]:
kpts.find_irreducible_lattice_points()

In [74]:
kpts.reciprocal_lattice.irreducible_lattice_points

array([[0, 0, 0],
       [1, 1, 0]])

In [75]:
kpts.reciprocal_lattice.lattice_points

array([[0, 0, 0],
       [1, 1, 0],
       [1, 2, 0]])

In [76]:
kpts.rlattice_to_kpoints(kpts.reciprocal_lattice.lattice_points)

array([[Fraction(0, 1), Fraction(0, 1), Fraction(0, 1)],
       [Fraction(2, 3), Fraction(1, 3), Fraction(0, 1)],
       [Fraction(1, 3), Fraction(2, 3), Fraction(0, 1)]], dtype=object)

In [77]:
kpts.irreducible_kpoints

array([[Fraction(0, 1), Fraction(0, 1), Fraction(0, 1)],
       [Fraction(2, 3), Fraction(1, 3), Fraction(0, 1)]], dtype=object)

In [78]:
kpts.irreducible_kpoints_index_map

array([0, 1, 1])

In [79]:
kpts.irreducible_kpoints_map

array([0, 1, 1])

In [80]:
kpts.irreducible_kpoints_trans

array(['E', 'E', 'I'], dtype='<U7')

In [81]:
kpts.irreducible_kpoints_mult

array([1, 2])

In [83]:
np.dot(kpts.reciprocal_lattice.lattice_points, kpts.rvec_bz)

array([[ 0.        ,  0.        ,  0.        ],
       [ 3.62759873,  2.0943951 ,  0.        ],
       [ 3.62759873, -2.0943951 ,  0.        ]])

In [85]:
np.dot(kpts.kpoints, kpts.rvec).astype(float)

array([[ 0.        ,  0.        ,  0.        ],
       [ 3.62759873,  2.0943951 ,  0.        ],
       [ 3.62759873, -2.0943951 ,  0.        ]])